#ifndef ___map_defines_inc
#define ___map_defines_inc 1

enum TileNum { TILE_SHIP, TILE_WHITE, TILE_ROCK1, TILE_ROCK2, TILE_ROCK3, TILE_ROCK4, TILE_ROCK5, TILE_ROCK6, TILE_RETICLE, TILE_PARTICLE, TILE_BEAMW, TILE_NUMBERS, TILE_DASHDOT, TILE_ALPHA, TILE_NOTILE, TILE_POWERUP, TILE_SHIELD, TILE_SHIPSHIELD, TILE_TITLESCREEN, TILE_LEVELUP, TILE_NEWGAME, TILE_QUIT, TILE_ROBOT, TILE_ROCKET, TILE_EXPLOSION, TILE_ROAD, TILE_BUILDING, TILE_GALAXIES, TILE_SMOKE, TILE_SUPERPOWERUP, TILE_LASER, TILE_MINERBOTHEAD, TILE_MINERBOTARM, TILE_MINERBOTCLAW,  TILE_CONNECTINGSCREEN, NUM_TILES };

#endif
